[package]
name = "expression"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]
edition = "2018"
[[bench]]
harness = false
name = "evaluate_expression"

[dependencies]
nom = "4.1.0"

[dev-dependencies]
criterion = "0.2.5"
maplit = "1.0.1"
