[package]
name = "expression"
version = "0.1.0"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"
[[bench]]
harness = false
name = "evaluate_expression"

[dependencies]
nom = "4.2.3"
common = { path = "../common" }

[dev-dependencies]
criterion = "0.2.11"
maplit = "1.0.1"
