[package]
name = "expression"
version = "0.1.0"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"
[[bench]]
harness = false
name = "evaluate_expression"

[dependencies]
nom = "5.0.0-beta2"
num-traits = "0.2.8"

[dev-dependencies]
criterion = "0.2.11"
maplit = "1.0.1"
